version: "2"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - metrics:metrics
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier
 
  metrics:
    tty: true
    stdin_open: true
    expose:
      - 9171
    image: infinityworks/github-exporter:latest 
    environment:
       - REPOS=freeCodeCamp/freeCodeCamp,docker/docker
       - GITHUB_TOKEN=<GitHub API Token see README>
    networks:
      - back-tier
